### ISSUE TITLE
Needs font end

### ISSUE THREAD

**Issue by oliverh57** [McTrees/remote-Minecraft#1]
![design](https://cdn.discordapp.com/attachments/376000295374815233/376682212772413440/unknown.png "design")

Boxes in the middle are for buttons

**Comment by jessopj1-zz** [comment]
noice

**Comment by oliverh57** [comment]
![design](https://cdn.discordapp.com/attachments/302765808109617153/376687690189635584/unknown.png "design")

html mock up of design
